# GRIP Task 1
## Function: Data Science and Business Analytics Intern

-----------
### Prediction using Supervised ML

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
dataset = pd.read_csv("student_scores.csv")

In [3]:
dataset

Hours  Scores
0     2.5      21
1     5.1      47
2     3.2      27
3     8.5      75
4     3.5      30
5     1.5      20
6     9.2      88
7     5.5      60
8     8.3      81
9     2.7      25
10    7.7      85
11    5.9      62
12    4.5      41
13    3.3      42
14    1.1      17
15    8.9      95
16    2.5      30
17    1.9      24
18    6.1      67
19    7.4      69
20    2.7      30
21    4.8      54
22    3.8      35
23    6.9      76
24    7.8      86

### Instantiating an empty model

In [4]:
model = LinearRegression()

### Split the data into train and test values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = dataset.iloc[:,0].values.reshape(-1,1)

In [7]:
y = dataset.iloc[:,1].values.reshape(-1,1)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Now train the model

In [9]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
y_pred = model.predict(X_test)

In [11]:
X_test

array([[1.5],
       [3.2],
       [7.4],
       [2.5],
       [5.9]])

In [12]:
y_pred

array([[16.88414476],
       [33.73226078],
       [75.357018  ],
       [26.79480124],
       [60.49103328]])

In [13]:
y_test

array([[20],
       [27],
       [69],
       [30],
       [62]], dtype=int64)

In [14]:
model.intercept_

array([2.01816004])

In [15]:
model.coef_

array([[9.91065648]])

In [16]:
print("y = {} + {}x".format(float(model.intercept_), float(model.coef_)))

y = 2.018160041434683 + 9.910656480642237x


### Dump the model in a pickle file.

In [17]:
import joblib

In [18]:
joblib.dump(model, "student_scores.pkl")

['student_scores.pkl']